export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="bira"

plugins=(sudo git docker history zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

alias ll="ls -lah"
alias vim="nvim"

export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
